export const fps = 30;
export const durationInFrames = 60 * fps;
export const scenes = [
  {
    from: 0,
    duration: 165,
    key: "question",
    label: "A CIDADE GERA DADOS",
    title: "Você consegue\nentender o que\neles dizem?",
    subtitle: "Informação pública só é útil quando chega com clareza.",
  },
  {
    from: 165,
    duration: 195,
    key: "brand",
    label: "A PLATAFORMA ESTÁ NO AR",
    title: "Paulo Afonso\nem Dados",
    subtitle: "Um portal gratuito, independente e feito para a população.",
  },
  {
    from: 360,
    duration: 225,
    key: "pipeline",
    label: "COMO FUNCIONA",
    title: "Da fonte oficial\npara uma consulta\nsimples.",
    subtitle: "A coleta busca atualizações nos dias úteis e registra o que mudou.",
  },
  {
    from: 585,
    duration: 300,
    key: "spending",
    label: "GASTOS COM CONTEXTO",
    title: "Veja o caminho\ndo dinheiro.",
    subtitle: "Reserva, entrega conferida e pagamento, com objeto, fornecedor e órgão.",
  },
  {
    from: 885,
    duration: 210,
    key: "stories",
    label: "NOVIDADES EM SEQUÊNCIA",
    title: "Conheça o\nP.A Stories.",
    subtitle: "Passe pelas atualizações e abra o registro que chamou sua atenção.",
  },
  {
    from: 1095,
    duration: 255,
    key: "council",
    label: "ATUAÇÃO POLÍTICA",
    title: "Projetos e pedidos\npor vereador.",
    subtitle: "Consulte matérias registradas e abra o documento publicado no SAPL.",
  },
  {
    from: 1350,
    duration: 240,
    key: "signals",
    label: "ANÁLISE SEM CAIXA PRETA",
    title: "Sinais calculados\npor regras claras.",
    subtitle: "Variações e concentrações ganham contexto, sem julgamento automático.",
  },
  {
    from: 1590,
    duration: 210,
    key: "end",
    label: "ABRA. PESQUISE. CONFIRA.",
    title: "A cidade\nfica mais clara\ncom você.",
    subtitle: "pauloafonsoemdados.baiustecnologia.com.br",
  },
];
